"use strict";
let car = 'subaru';
console.log("is car == 'subaru'? i predict ture.");
console.log(car == 'subaru');
console.log("is car === 'subaru'? i predict ture.");
console.log(car === 'subaru');
console.log("is car != 'subaru'? i predict false.");
console.log(car != 'subaru');
console.log("is car !== 'subaru'? i predict false.");
console.log(car !== 'subaru');
console.log("is car > 'subaru'? i predict false.");
console.log(car > 'subaru');
console.log("is car < 'subaru'? i predict false.");
console.log(car < 'subaru');
console.log("is car >='subaru'? i predict false.");
console.log(car >= 'subaru');
console.log("is car ? i predict ture.");
console.log(car);
